export type Coordinate = {
  x: number;
  y: number;
  floor: number;
};

export type TileType = 'CONCRETE' | 'WALL' | 'MUD' | 'STAIRS_UP' | 'STAIRS_DOWN' | 'STAIRS' | 'EMPTY';

export type TileMetadata = {
  noiseCoefficient: number; // 1.0 = normal, >1.0 = loud (e.g. mud/glass), <1.0 = quiet
  spawnWeight: number;      // Probability of enemy spawn
  isInteractable: boolean;
  opacity: number;          // 0 = transparent, 1 = opaque (blocks vision)
  walkable: boolean;
};

export type Tile = {
  coordinate: Coordinate;
  type: TileType;
  metadata: TileMetadata;
};

export type FloorData = Tile[][][]; // [z][x][y]

export type UnitStatus = {
  hp: number;
  maxHp: number;
  ap: number;
  maxAp: number;
  apRecovery: number; // AP recovered per turn
  sightRange: number; // Distance unit can see/detect targets
  isInjured: boolean; // Increases noise, movement cost
  noiseLevel: number; // Noise generated by this unit (for hearing)
  movementMode?: 'RUN' | 'SNEAK'; // Default RUN

export type ActionType = 'MOVE' | 'ATTACK' | 'CLIMB';
export type Faction = 'PLAYER' | 'ENEMY';
export type UnitType = 'PLAYER' | 'ENEMY';

export type AIMemory = {
  lastKnownTargetPos?: Coordinate;
  state: 'IDLE' | 'SLEEP' | 'WANDER' | 'CHASE' | 'SEARCH' | 'ATTACK';
};

export type Unit = {
  id: string;
  type: UnitType;
  faction: Faction;
  name: string;
  position: Coordinate;
  status: UnitStatus;
  facing: 'UP' | 'DOWN' | 'LEFT' | 'RIGHT'; // For sprite direction
  memory?: AIMemory; // Only for AI
};

export type Action = {
  id: string;
  type: 'MOVE' | 'WAIT' | 'INTERACT' | 'ATTACK' | 'CLIMB'; // Added ATTACK
  unitId: string;
  target?: Coordinate; // For move
  targetUnitId?: string; // For attack
  cost: number;
  status: 'QUEUED' | 'EXECUTING' | 'COMPLETED';
};

export type GamePhase = 'DECISION' | 'EXECUTION';

export type DamageEvent = {
  id: string;
  position: Coordinate;
  amount: number;
  timestamp: number;
};

export interface GameState {
  floor: FloorData;
  units: Record<string, Unit>;
  phase: GamePhase;
  timer: number;
  actionQueue: Action[];
  seed: number;
  visibleTiles: Set<string>; // Coordinate "x,y"
  exploredTiles: Set<string>; // Coordinate "x,y"
  debugFow: boolean;
  damageEvents: DamageEvent[];
}

export interface GameActions {
  initGame: (seed?: number) => void;
  setPhase: (phase: 'DECISION' | 'EXECUTION') => void;
  updateTimer: (deltaTime: number) => void;
  addUnit: (unit: Unit) => void;
  updateUnitPosition: (unitId: string, position: Coordinate) => void;
  updateUnitStatus: (unitId: string, status: Partial<Unit['status']>) => void;
  queueAction: (action: Action) => void;
  cancelAction: () => void;
  clearActionQueue: () => void;
  toggleDebugFow: () => void;
  applyDamage: (targetId: string, amount: number) => void;
  removeDamageEvent: (eventId: string) => void;
  toggleSneak: (unitId: string) => void;
}
